apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::744781939271:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ZTKK66CT8YTH
      username: system:node:{{EC2PrivateDNSName}}
    -groups:
      - system:masters
      rolearn: arn:aws:iam::744781939271:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-15T05:29:22Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
    manager: vpcLambda
    operation: Update
    time: "2022-08-15T05:29:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1655"
  uid: d481a690-cb9a-47ad-9dec-2a3f7b2a97ac
